server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:43306/youtubeDB
    username: root
    password: 1234
  batch:
    job:
      name: ${job.name}
    jdbc:
      initialize-schema: always
  jpa:
    hibernate:
      ddl-auto: update